version: '2.1'

services:
  #Mura Server
  wheelie_mssql_cfml:
    image: ortussolutions/commandbox:latest
    depends_on:
      - wheelie_mssql
    environment:
      PORT: 8080
      SSL_PORT: 8443
      CFENGINE: adobe@2016
      CFCONFIG_ADMINPASSWORD: NOT_SECURE_CHANGE
      WHEELIE_ADMIN_USERNAME: admin
      WHEELIE_ADMIN_PASSWORD: admin
      WHEELIE_ADMINEMAIL: example@localhost.com
      WHEELIE_APPRELOADKEY: appreload
      WHEELIE_DATASOURCE: wheeliedb
      WHEELIE_DATABASE: wheeliedb
      WHEELIE_DBTYPE: mssql
      WHEELIE_DBUSERNAME: sa
      WHEELIE_DBPASSWORD: NOT_SECURE_CHANGE_a1
      WHEELIE_DBHOST: wheelie_mssql
      WHEELIE_DBPORT: 1433
      WHEELIE_SITEIDINURLS: "false"
      WHEELIE_INDEXFILEINURLS: "false"
      WHEELIE_TESTBOX: "true"
    volumes:
        - ../../../:/app
    ports:
        - "8080:8080"

  #MSSQL
  wheelie_mssql:
    image: microsoft/mssql-server-linux:latest
    environment:
       ACCEPT_EULA: Y
       SA_PASSWORD: NOT_SECURE_CHANGE_a1
    volumes:
        - wheelie_mssql_data:/var/opt/mssql
    ports:
        - "1433:1433"

volumes:
    wheelie_mssql_data:
