version: '2.1'

services:
  wheelie_cfml2:
    image: ortussolutions/commandbox:alpine
    environment:
      PORT: 8080
      SSL_PORT: 8443

      # Set your coldfusion setting here
      CFENGINE: lucee@5.2.1+9
      CFCONFIG_ADMINPASSWORD: NOT_SECURE_CHANGE

      # Set your wheelie config here
      WHEELIE_APPRELOADPASS: wheelie
      WHEELIE_DEFAULTEMAIL: default@getwheelie.com
      WHEELIE_NOREPLYEMAIL: noreply@getwheelie.com
      WHEELIE_ADMINEMAIL: admin@getwheelie.com
      WHEELIE_ERROREMAILADDRESS: error@getwheelie.com
      WHEELIE_ADMINFROMEMAIL: admin@getwheelie.com
      WHEELIE_EMAILONERROR: "true"
      WHEELIE_URLREWRITING: "on"
      WHEELIE_REWRITEFILE: index.cfm
      WHEELIE_PASSWORDSALT: OkIeKNKoIvbZMFPuMJ3EMQ==
      WHEELIE_ADMINURLPATH: /manager

      # Set your database settings here
      WHEELIE_DATASOURCE: wheelie
      WHEELIE_DATABASE: wheeliedb
      WHEELIE_DBTYPE: mysql
      WHEELIE_DBUSERNAME: root
      WHEELIE_DBPASSWORD: password
      WHEELIE_DBHOST: localhost
      WHEELIE_DBPORT: 3306

      # Set your email config here
      WHEELIE_SMTP_SERVER: smtp.sendgrid.net
      WHEELIE_SMTP_USERNAME: yoursendgridusername
      WHEELIE_SMTP_PASSWORD: sendgridpass
      WHEELIE_SMTP_PORT: 587
      WHEELIE_SMTP_USETLS: "true"
    volumes:
      - .:/app
    ports:
      - "80:8080"
      - "443:8443"
