version: '2.1'

services:
  wheelie_cfml:
    image: ortussolutions/commandbox:lucee5
    environment:
      PORT: 8080
      SSL_PORT: 8443
      CFENGINE: lucee@5.2.4+37
      CFCONFIG_ADMINPASSWORD: NOT_SECURE_CHANGE
      WHEELIE_APPRELOADPASS: wheelie
      WHEELIE_DEFAULTEMAIL: default@getwheelie.com
      WHEELIE_NOREPLYEMAIL: noreply@getwheelie.com
      WHEELIE_ADMINEMAIL: admin@getwheelie.com
      WHEELIE_ERROREMAILADDRESS: error@getwheelie.com
      WHEELIE_ADMINFROMEMAIL: admin@getwheelie.com
      WHEELIE_EMAILONERROR: "true"
      WHEELIE_URLREWRITING: "on"
      WHEELIE_REWRITEFILE: index.cfm
      WHEELIE_PASSWORDSALT: OkIeKNKoIvbZMFPuMJ3EMQ==
      WHEELIE_ADMINURLPATH: /manager
      WHEELIE_DATASOURCE: wheelie
      WHEELIE_DATABASE: wheeliedb
      WHEELIE_DBTYPE: mysql
      WHEELIE_DBUSERNAME: root
      WHEELIE_DBPASSWORD: NOT_SECURE_CHANGE
      WHEELIE_DBHOST: wheelie_mysql_db
      WHEELIE_DBPORT: 3306
      WHEELIE_SMTP_SERVER: smtp.sendgrid.net
      WHEELIE_SMTP_USERNAME: yoursendgridusername
      WHEELIE_SMTP_PASSWORD: sendgridpass
      WHEELIE_SMTP_PORT: 587
      WHEELIE_SMTP_USETLS: "true"
    volumes:
      - .:/app
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - dbnet
    # depends_on:
    #   mysql:
    #       condition: service_healthy

  wheelie_mysql_db:
    image: mysql:latest
    ports:
      - "55555:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'NOT_SECURE_CHANGE'
      MYSQL_DATABASE: wheeliedb
      MYSQL_USER: 'wheelie'
      MYSQL_PASSWORD: 'NOT_SECURE_CHANGE'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -pB@nneroftruth1989 ping --silent"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./build/docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./build/docker/mysql/data:/var/lib/mysql
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge
